export const dataContainers: Databindings.BindingsContainer = {
  Generic: 'Translate',
  Catalogue: 'Translate',
  Poster: 'bounty_board_data',
  LegendaryPoster: 'bounty_board_data',
  AdvertPoster: 'bounty_board_data',
  CatalogItemInspection: 'DynamicCatalogItems',
  price_details: 'ShelfItemInspection',
  bottomRightStack: 'MpHudDataStore',
};

export const bindingTypes: Databindings.BindingTypes = {
  Generic: {
    textField0: 'container',
    textField0Strike: 'container',
    divider0: 'container',
    textField1: 'container',
    textField1Strike: 'container',
    divider1: 'container',
    textField2: 'container',
    textField2Strike: 'container',
    divider2: 'container',
    textField3: 'container',
    textField3Strike: 'container',
    divider3: 'container',
    textField4: 'container',
    textField4Strike: 'container',
    divider4: 'container',
    textField5: 'container',
    textField5Strike: 'container',
    divider5: 'container',
    textField6: 'container',
    textField6Strike: 'container',
    divider6: 'container',
    textField7: 'container',
    textField7Strike: 'container',
    divider7: 'container',
    textField8: 'container',
    textField8Strike: 'container',
    divider8: 'container',
    textField9: 'container',
    textField9Strike: 'container',
    divider9: 'container',
    textField10: 'container',
    textField10Strike: 'container',
    divider10: 'container',
    textField11: 'container',
    textField11Strike: 'container',
    divider11: 'container',
    textField12: 'container',
    textField12Strike: 'container',
    divider12: 'container',
    textField13: 'container',
    textField13Strike: 'container',
    divider13: 'container',
    textField14: 'container',
    textField14Strike: 'container',
    divider14: 'container',
    textField15: 'container',
    textField15Strike: 'container',
    divider15: 'container',
    textField16: 'container',
    textField16Strike: 'container',
    divider16: 'container',
    textField17: 'container',
    textField17Strike: 'container',
    divider17: 'container',
    textField18: 'container',
    textField18Strike: 'container',
    divider18: 'container',
    textField19: 'container',
    textField19Strike: 'container',
    divider19: 'container',
    textField20: 'container',
    textField20Strike: 'container',
    divider20: 'container',
    textField21: 'container',
    textField21Strike: 'container',
    divider21: 'container',
    textField22: 'container',
    textField22Strike: 'container',
    divider22: 'container',
    textField23: 'container',
    textField23Strike: 'container',
  },
  Catalogue: {
    textField0: 'container',
    divider0: 'container',
    textField1: 'container',
    divider1: 'container',
    textField2: 'container',
    divider2: 'container',
    textField3: 'container',
    divider3: 'container',
    textField4: 'container',
    divider4: 'container',
    textField5: 'container',
    divider5: 'container',
    textField6: 'container',
    divider6: 'container',
    textField7: 'container',
    divider7: 'container',
    textField8: 'container',
    divider8: 'container',
    textField9: 'container',
    divider9: 'container',
    textField10: 'container',
    divider10: 'container',
    textField11: 'container',
    divider11: 'container',
    textField12: 'container',
    divider12: 'container',
    textField13: 'container',
    divider13: 'container',
    textField14: 'container',
    divider14: 'container',
    textField15: 'container',
    divider15: 'container',
    textField16: 'container',
    divider16: 'container',
    textField17: 'container',
    divider17: 'container',
    textField18: 'container',
    divider18: 'container',
    textField19: 'container',
    divider19: 'container',
    textField20: 'container',
    divider20: 'container',
    textField21: 'container',
    divider21: 'container',
    textField22: 'container',
    divider22: 'container',
    textField23: 'container',
    divider23: 'container',
    textField24: 'container',
    divider24: 'container',
  },
  Poster: {
    isVisible: 'bool',
    isDiffVisible: 'bool',
    type: 'int',
    difficulty: 'int',
    price: 'string',
    body: 'string',
    header: 'string',
    name: 'string',
    tex: 'hash',
    txd: 'hash',
  },
  LegendaryPoster: {
    isVisible: 'bool',
    tex: 'hash',
    txd: 'hash',
    header: 'string',
    setDifficulty: 'int',
  },
  AdvertPoster: {
    isVisible: 'bool',
    tex: 'hash',
    txd: 'hash',
  },
  CatalogItemInspection: {
    isVisible: 'bool',
    itemLabel: 'hash',
    itemDescription: 'string',
    purchaseLabel: 'string',
    purchasePrice: 'int',
    tokenPrice: 'int',
    isGoldPrice: 'bool',
    purchaseModifiedPrice: 'int',
    modifiedPriceVisible: 'bool',
    modifiedPriceGold: 'bool',
    ammoVisible: 'bool',
    ammoCurrent: 'int',
    ammoMax: 'int',
    ammoTextureDictionary: 'string',
    ammoTexture: 'string',
    mailVisible: 'bool',
    mailCurrent: 'int',
  },
  price_details: {
    purchasePrice: 'int',
    isGoldPrice: 'bool',
    modifiedPriceVisible: 'bool',
    modifiedPriceGold: 'bool',
    purchaseModifiedPrice: 'int',
  },
  bottomRightStack: {
    isVisible: 'bool',
  },
};

export const dataTypes: Databindings.DataTypes = {
  Generic: 'Generic',
  Catalogue: 'Catalogue',
  Poster0: 'Poster',
  Poster1: 'Poster',
  Poster2: 'Poster',
  legendaryPoster0: 'LegendaryPoster',
  legendaryPoster1: 'LegendaryPoster',
  legendaryPoster2: 'LegendaryPoster',
  advertPoster0: 'AdvertPoster',
  advertPoster1: 'AdvertPoster',
  advertPoster2: 'AdvertPoster',
  CatalogItemInspection: 'CatalogItemInspection',
  price_details: 'price_details',
  bottomRightStack: 'bottomRightStack',
};

export const rootBindingTypes: Databindings.RootBindingTypes = {
  helperTextfields: {
    rawLabel0: 'string',
    rawLabel1: 'string',
    rawValue0: 'string',
    rawValue1: 'string',
  },
  MPCountdown: {
    showTimer: 'bool',
    Timer: 'string',
  },
  PostMatchAndLeaderboard: {
    Title: 'container',
    LeaderboardList: 'list',
  },
  FastTravel: {
    header: 'string',
    subHeader: 'string',
    description: 'string',
    subFooter: 'string',
    locationList: 'list',
  },
};

export const rootDataTypes: Databindings.RootDataTypes = {
  helperTextfields: 'helperTextfields',
  MPCountdown: 'MPCountdown',
  PostMatchAndLeaderboard: 'PostMatchAndLeaderboard',
  FastTravel: 'FastTravel',
};

export const containerBindingTypes: Record<string, Record<string, Databindings.BindingType>> = {
  // TODO: ?
};

export const listBindingTypes: Record<string, Record<string, Databindings.BindingType>> = {
  LeaderboardList: {
    info_visible_06: 'bool',
    info_visible_07: 'bool',
    info_visible_08: 'bool',
    info_value_06: 'string',
    info_value_07: 'string',
    info_value_08: 'string',
    LeaderboardListItem: 'container[]',
  },
  LeaderboardListItem: {
    Position: 'int',
    ShowCross: 'bool',
    CrossColor: 'hash',
    Gamertag: 'string',
    GamertagColor: 'int',
    ShowCrewTag: 'bool',
    CrewTag: 'string',
    ShowRank: 'bool',
    Rank: 'string',
    Spectating: 'bool',
    Stat0: 'string',
    Stat1: 'string',
    Stat2: 'string',
    Stat3: 'string',
    ShowBlip: 'bool',
    BlipColor: 'int',
    Blip: 'string',
    isHighlighted: 'bool',
    HeadsetIconVisible: 'bool',
    HeadsetIconColor: 'hash',
    SetOverlayImg: 'int',
    ShowOverlay: 'bool',
    AvatarDictionary: 'string',
    AvatarTexture: 'string',
    AvatarAlpha: 'int',
  },
  locationList: {
    Fast_Travel_Location: 'container[]',
  },
  Fast_Travel_Location: {
    dynamic_list_item_enabled: 'bool',
    dynamic_list_item_visible: 'bool',
    dynamic_list_item_main_color: 'hash',
    dynamic_list_item_secondary_color: 'hash',
    dynamic_list_item_tertiary_color: 'hash',
    dynamic_list_item_raw_text_entry: 'string',
    dynamic_list_item_text_label_entry: 'hash',
    dynamic_list_item_secondary_raw_text_entry: 'string',
    dynamic_list_item_secondary_text_visible: 'bool',
    dynamic_list_item_secondary_text_enabled: 'bool',
    dynamic_list_item_extra_int_field_one_value: 'int',
    dynamic_list_item_extra_int_field_two_value: 'int',
    dynamic_list_item_extra_text_field_entry_two_visibility: 'bool',
    dynamic_list_item_extra_int_field_three_value: 'int',
    dynamic_list_item_extra_text_field_entry_three_visibility: 'bool',
  },
};
