PCF = {
    [6] = 'DontInfluenceWantedLevel',
    [7] = 'DisableLockonToRandomPeds',
    [11] = 'Knockedout',
    [12] = 'IsAimingGun',
    [40] = 'CanAttackFriendly',
    [43] = 'DisableLadderClimbing',
    [127] = 'Setting as ped to not behave like law/cop',
    [136] = 'Can not be ridden',
    [138] = 'OneShotWillKillPed',
    [154] = 'UseFollowLeaderThreatResponse',
    [158] = 'RequestStealthMovement',
    [167] = 'ShouldBeOnMount',
    [169] = 'DisableGrappleByPlayer',
    [178] = 'AllowNonTempExceptionEvents',
    [194] = 'ShouldPedFollowersIgnoreWaypointMBR',
    [207] = 'FlamingHoovesActive',
    [211] = 'GiveAmbientDefaultTaskIfMissionPed',
    [214] = 'Not mountable by AI',
    [217] = 'Suppress shocking events',
    [246] = 'ForcePedLoadCover',
    [263] = 'NoCriticalHits',
    [264] = 'UpperBodyDamageAnimsOnly',
    [265] = 'Can drown in water',
    [280] = 'DontEnterLeadersVehicle',
    [287] = 'AllowMissionDriverlessDraftAnimalResponse',
    [297] = 'ForceInteractionLockonOnTargetPed',
    [305] = 'DisableHeadGore',
    [306] = 'Disable Dismemberment',
    [312] = 'DisableHorseGunshotFleeResponse',
    [319] = 'EnableAsVehicleTransitionDestination',
    [336] = 'ForceInjuredMovement',
    [337] = 'DontExitVehicleIfNoDraftAnimals',
    [340] = 'DisableAllMeleeTakedowns',
    [361] = 'Ignore Weapon Degradation',
    [366] = 'DisableVehicleTransitions',
    [370] = 'DisableDeadEyeTagging',
    [373] = 'AllowSlipstream',
    [388] = 'DisableFatallyWoundedBehaviour',
    [412] = 'BlockHorsePromptsForTargetPed',
    [419] = 'BlockMountHorsePrompt',
    [421] = 'AllowDoorBargingUnderCombat',
    [437] = 'DisableWeatherConditionPerceptionChecks',
    [445] = 'DisableDoorBarge',
    [448] = 'TreatAsMissionPopTypeForSpeech',
    [451] = 'HorseDontEvaluateRiderForDamageChecks',
    [467] = 'DisableHonorModifiers',
    [558] = 'Enabling guard investigation behaviour',
    [560] = 'EnableMountCoverForPedInMP',
    [580] = 'IsTranquilized',
    [582] = 'AllowStudyInMP',
    [540] = 'FollowLeaderRunToEnterTransport',
    [550] = 'DisableAndBreakAimLockOntoThisPed',
    [561] = 'EnableHorseCollectPlantInteractionInMP',
    [565] = 'valid for vehicle seat stow',
    [566] = 'EnableSpecialActionBranches',
    [567] = 'DisableHorseShunting',
    [569] = 'CanBeAttackedByFriendlyPed',
    [575] = 'DisableGuardAI',
    [592] = 'Disable full body hit reacts',
    [595] = 'AllowAutoSwitchToProjectiles',
    [599] = 'DisableScenarioWarpWeaponDestruction',
    [600] = 'SkipOwnershipCheckForHorseToEquipWeapons',
}

-- 174 = disable evasive step?
-- 593 = true = Eagle Eye Skill not unlocked at rank
-- 593 = false = Eagle Eye Skill unlocked at rank

-- PCF_PreventAutoShuffleToDriversSeat

PRF = {
    [129] = 'DisableDynamicPlayerScenarios',
    [187] = 'DisableAmbientPrompts',
    [364] = 'IgnoreDrownAndKillVolumes',
}
