STRING_GENERIC = {
  "TRAINS1",
  "TRAINS2",
  "TRAINS3",
  "TROLLEY1",
  "TROLLEY2",
  "TROLLEY3",
  "TROLLEY4",
  "MINECART_JAM3_4",
  "RIVERS1",
  "TROLLEY_INTERSECTION2",
  "TROLLEY_INTERSECTION3",
  "TROLLEY_INTERSECTION5",
  "TRAINS_NB1",
  "TRAINS_NB2",
  "TRAINS_NB3",
  "TRAINS_ROB3",
  "TRAINS_INTERSECTION1_3",
  "TRAINS_INTERSECTION2_3",
  "TRAINS_INTERSECTION1_ANN",
  "TRAINS_INTERSECTION2_ANN",
  "TRAINS_INTERSECTION3_COR",
  "TRAINS_INTERSECTION1_APP",
  "TRAINS_ROB3",
  "TRAINS_OLD_WEST03",
  "TRAINS_OLD_WEST02",
  "TRAINS_OLD_WEST01",
  "TRAINS_OLD_WEST_INTERSECTION02",
  "TRAINS_OLD_WEST_INTERSECTION01",
  "FREIGHT_NB1_INTER",
  "FREIGHT_GROUP",
}

HASH_GENERIC = {}

for k, v in pairs(STRING_GENERIC) do
    local model = GetHashKey(v)
    if HASH_GENERIC[model] then
        print('Overlap: ' .. HASH_GENERIC[model] .. ' | ' .. v)
    end
    print(model .. ' | ' .. v)
    HASH_GENERIC[model] = v
end
